### PR TITLE
[WIP] Data Explorer table styling changes

### PR DESCRIPTION
**Pull request by javag97**
I created a thread to have back and forth conversations regarding some table visual changes to data explorer. 

Screen Shot 2020-02-15 at 4 30 46 PM

From someone unfamiliar with data, I thought design work here would be the easiest to assess and make changes quickly. Inspiration for this was primarily taken from Google Spreadsheets and Airtable. @emeeks suggested some changes according to [best practices among table design](https://www.darkhorseanalytics.com/blog/clear-off-the-tableurl). I have not yet finished implementing all of the style changes as suggested.

Some other things to note in general that I wanted to work on
1. Filtering interaction
1. Styling of buttons to change to various graphs/charts to include labels.
1. Limiting the use of color for visualizations. 

I also had a question about pagination and existing 20-row defaults. What was the thought process behind us doing that? I was considering suggesting changes, but it is difficult to do so without getting the right context.  

I figured this to be a good starting point for feedback.  Let me know what thoughts we have on what I've worked on so far, but whether there is some low hanging fruit that I can tackle and that this project can benefit a lot from.

### CODE REVIEW

**Comment by emeeks** [comment]
The new table looks really good. A couple points:
1. The background in the new filters is transparent, so as soon as you scroll, you see the table behind them, so they should have white backgrounds. (see screenshot below)
2. You mention reducing color in the Dataviz but I don't see it, where is this happening?
Screen Shot 2020-02-16 at 1 30 50 AM

**Comment by javag97** [comment]
Ah (1,2,3) are things that I wanted to work on next! Let me see what I can do.

**Comment by emeeks** [comment]
Oh sure, that makes sense, sorry for misreading.

**Comment by javag97** [comment]
No worries at all. I don't think I made it that clear. For this PR, I can fix the bugs you brought up and work on some of the other items in another PR so that this can get merged in.

**Pull request merged**
